export const tokenDescriptions = {
    'Keyword': 'Una palabra reservada en JavaScript, como `if`, `else`, `function`, etc.',
    'Identifier': 'Un nombre de variable, función, o etiqueta.',
    'Numeric': 'Un valor numérico.',
    'String': 'Una secuencia de caracteres entre comillas.',
    'Punctuator': 'Un carácter que tiene una función gramatical, como `=`, `+`, `;`, etc.',
    'RegularExpression': 'Una expresión regular.',
    'Boolean': 'Un valor booleano, `true` o `false`.',
    'Null': 'El valor nulo `null`.',
    'Template': 'Una plantilla de cadena que permite la interpolación de expresiones.',
    'Comment': 'Un comentario que puede ser de línea (//) o de bloque (/* */).',
    'WhiteSpace': 'Un espacio en blanco en el código, que puede incluir espacios, tabulaciones y saltos de línea.',
    'Literal': 'Un valor literal, como una cadena, número, booleano, `null`, o `undefined`.',
    'Undefined': 'El valor indefinido `undefined`, usado para variables no asignadas o propiedades no existentes.',
    'Object': 'Una colección de pares clave-valor.',
    'Array': 'Una lista ordenada de valores.',
    'Function': 'Una función, que es un bloque de código diseñado para realizar una tarea específica.',
    'ArrowFunction': 'Una función flecha, una sintaxis más corta para escribir funciones expresión.',
    'Class': 'Una clase, que es un tipo de función para crear objetos y manejar la herencia.',
    'Method': 'Un método, que es una función asociada a un objeto o clase.',
    'This': 'El contexto actual del objeto, utilizado dentro de las funciones y métodos.',
    'Super': 'Una referencia al objeto padre de una clase, utilizado para acceder a funciones o propiedades de la clase padre.',
    'Object': 'Una colección de pares clave-valor.',
    'Array': 'Una lista ordenada de valores.',
    // Añade más tipos y descripciones según sea necesario
};
